<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Mailling\Mailling.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
      <ProjectReference Include="..\Modules.Notifications.Contracts\Modules.Notifications.Contracts.csproj" />
    </ItemGroup>

</Project>
