<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Mediator.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Core\Core.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="v1\Roles\DeleteRole\" />
      <Folder Include="v1\Roles\GetRoles\" />
      <Folder Include="v1\Roles\GetRoleWithPermissions\" />
      <Folder Include="v1\Roles\GetRole\" />
      <Folder Include="v1\Roles\UpdatePermissions\" />
    </ItemGroup>

</Project>
