<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\MessageBus\MessageBus.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Storage\Storage.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
      <ProjectReference Include="..\Modules.Multitenancy.Contracts\Modules.Multitenancy.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Finbuckle.MultiTenant" />
      <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" />
      <PackageReference Include="Finbuckle.MultiTenant.EntityFrameworkCore" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Mediator.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\v1\TenantProvisioning\" />
      <Folder Include="Features\v1\UpdateTenantTheme\" />
    </ItemGroup>

</Project>
