<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Caching\Caching.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Jobs\Jobs.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Mailling\Mailling.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\MessageBus\MessageBus.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Storage\Storage.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
      <ProjectReference Include="..\..\Auditing\Modules.Auditing.Contracts\Modules.Auditing.Contracts.csproj" />
      <ProjectReference Include="..\Modules.Identity.Contracts\Modules.Identity.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Finbuckle.MultiTenant.Identity.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="UAParser" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\v1\Groups\" />
      <Folder Include="Features\v1\Roles\" />
    </ItemGroup>

</Project>
